#!/usr/bin/env python3
from __future__ import annotations

import json
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "python_sdk" / "lark_cli_sdk" / "command_catalog.json"
OUTPUT_PATH = ROOT / "python_sdk" / "COMMAND_REFERENCE.md"


@dataclass(frozen=True)
class CommandDoc:
    path: str
    use: str
    short: str
    mode: str
    method_name: str
    required_flags: list[str]
    flags_preview: list[str]


def _path_to_method_name(path: str) -> str:
    parts: list[str] = []
    for raw in path.split():
        token = raw.strip().lstrip("+").replace("-", "_")
        if token:
            parts.append(token)
    return "cmd_" + "_".join(parts)


def _flag_preview(flag: dict[str, Any]) -> str:
    name = str(flag.get("name", "")).strip()
    if not name:
        return ""
    ftype = str(flag.get("type", "string"))
    required = bool(flag.get("required", False))
    hidden = bool(flag.get("hidden", False))

    suffix: list[str] = [ftype]
    if required:
        suffix.append("required")
    if hidden:
        suffix.append("hidden")
    return f"--{name} ({', '.join(suffix)})"


def load_commands() -> list[CommandDoc]:
    payload = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    result: list[CommandDoc] = []
    for item in payload.get("commands", []):
        path = str(item.get("path", "")).strip()
        if not path:
            continue
        flags = item.get("flags", [])
        required_flags: list[str] = []
        preview: list[str] = []
        for raw in flags:
            if not isinstance(raw, dict):
                continue
            name = str(raw.get("name", "")).strip()
            if not name:
                continue
            if bool(raw.get("required", False)):
                required_flags.append(f"--{name}")
            shown = _flag_preview(raw)
            if shown:
                preview.append(shown)
        result.append(
            CommandDoc(
                path=path,
                use=str(item.get("use", "")).strip(),
                short=str(item.get("short", "")).strip(),
                mode=str(item.get("mode", "sync")).strip() or "sync",
                method_name=_path_to_method_name(path),
                required_flags=required_flags,
                flags_preview=preview,
            )
        )
    return result


def render_markdown(commands: list[CommandDoc]) -> str:
    mode_counts = Counter(c.mode for c in commands)
    root_counts = Counter(c.path.split()[0] for c in commands)
    by_root: dict[str, list[CommandDoc]] = defaultdict(list)
    for command in commands:
        by_root[command.path.split()[0]].append(command)

    lines: list[str] = []
    lines.append("# Python SDK Command Reference")
    lines.append("")
    lines.append("Auto-generated from `python_sdk/lark_cli_sdk/command_catalog.json`.")
    lines.append("Do not edit this file manually. Re-generate with:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 python_sdk/scripts/generate_command_reference.py")
    lines.append("```")
    lines.append("")
    lines.append("## Coverage")
    lines.append("")
    lines.append(f"- Total commands: `{len(commands)}`")
    lines.append(
        f"- Modes: "
        + ", ".join(f"`{name}`={count}" for name, count in sorted(mode_counts.items()))
    )
    lines.append(f"- Top-level groups: `{len(root_counts)}`")
    lines.append("")
    lines.append("## How To Call Any Command")
    lines.append("")
    lines.append("- Preferred: call generated method in `LarkCLIClient`, e.g. `client.cmd_docs_search(...)`.")
    lines.append("- Fallback: call `client.run([...])` for commands that rely on positional arguments.")
    lines.append("- Flag mapping: `--page-limit` -> `page_limit`; bool `True` -> `--flag`; bool `False` -> `--flag=false`.")
    lines.append("- Repeated string flags: pass `list`/`tuple`, SDK expands them into repeated flags.")
    lines.append("")
    lines.append("## Full Command List")
    lines.append("")

    for root in sorted(by_root):
        entries = sorted(by_root[root], key=lambda c: c.path)
        lines.append(f"### `{root}` ({len(entries)})")
        lines.append("")
        lines.append("| CLI path | Python method | Mode | Required flags | Use | Short |")
        lines.append("|---|---|---|---|---|---|")
        for c in entries:
            required = ", ".join(c.required_flags) if c.required_flags else "-"
            use = c.use.replace("|", "\\|")
            short = c.short.replace("|", "\\|")
            lines.append(
                f"| `{c.path}` | `{c.method_name}` | `{c.mode}` | `{required}` | `{use}` | {short} |"
            )
        lines.append("")
        lines.append("<details>")
        lines.append("<summary>Show flags</summary>")
        lines.append("")
        for c in entries:
            lines.append(f"- `{c.path}`")
            if c.flags_preview:
                lines.append(f"  - {', '.join(c.flags_preview)}")
            else:
                lines.append("  - (no flags)")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    commands = load_commands()
    markdown = render_markdown(commands)
    OUTPUT_PATH.write_text(markdown + "\n", encoding="utf-8")
    print(f"generated: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
